name: artist
source:
  type: postgres
  connection:
    host: localhost
    port: 5432
    database: chinook_auto_increment
    user: postgres
    password: '123456'
  table: artist
description: The artist table contains information about music artists.
columns:
- name: artist_id
  type: integer
  description: Unique identifier for each artist in the table and this field is not null.
- name: name
  type: string
  description: The name of the artist.
